% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Oct-2019 20:42:06
%  MATLAB version: 9.7.0.1190202 (R2019b)
% -------------------------------------------------------------------
                                 

angle = 56.548667764616219;

ans = 0;

aspectRatio = 1;

avg = -6.4605184922257655;

backgroundOffset = [0.5 0.5 0.5 0];

black = 0;

contrast = 0.6;

cueFrames = 42;

cueSecs = 0.7;

disableNorm = 1;

escapeKey = 27;

feedbackFrames = 30;

feedbackSecs = 0.5;

fixationFrames = 18;

fixationSecs = 0.3;

frame = 17;

freq = 0.05;

gaborDimPix = 100;

gaborFrames = 9;

gaborSecs = 0.15;

gabortex = 11;

grey = 0.5;

h = 540;

i = 8;

ifi = 0.0166549419995863;

j = 8;

keyCode = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 ...
           0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
           0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
           0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
           0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
           0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
           0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
           0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
           0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0];

keyIsDown = 1;

leftKey = 37;

numCycles = 5;

orientarr = [-13.122856005178154 -5.959189266326443 -5.30981281079157 -11.04640389495162 ...
             -1.6968566296537704 -1.703861685617353 -6.6110515985990359 ...
             -5.1513490465911485];

orientation = 0;

phase = 0;

preContrastMultiplier = 0.5;

propertiesMat = [0 0.05 20 0.6 1 0 0 0];

r = 400;

respToBeMade = true;

responseFrames = 180;

responseSecs = 3;

rightKey = 39;

screenNumber = 0;

screenXpixels = 1920;

screenYpixels = 1080;

secs = 253500.8501913;

sigma = 20;

topPriorityLevel = 1;

trial = 1;

vbl = 253500.84981591505;

w = 960;

waitframes = 1;

white = 1;

window = 10;

windowRect = [0 0 1920 1080];

xCenter = 960;

yCenter = 540;

